### ISSUE TITLE
Remove Powershell Core dependencies

### ISSUE THREAD

**Issue by lturmel** [expertasolutions/AzureADApplicationExtensions#22]
Remove Powershell Core dependencies to ensure portability over difference AzureDevOps build agent

**Comment by lturmel** [comment]
Change status:

- GetAzureAdApplicationId: InProgress
- ManageAzureAdApplication: Next
- RemoveAzureADApplication: None

**Comment by lturmel** [comment]
Change status:

GetAzureAdApplicationId: Done
ManageAzureAdApplication: Done
RemoveAzureADApplication: InProgress

**Comment by expertasolutions** [comment]
completed !
